### PR TITLE
Expose noScroll globally if window is defined

### PR DESCRIPTION
**Pull request by esseb**
Currently the library only works when it's imported or required, but for my current project I need this library to work when just concatenated in a single `app.js` file together with the rest of my code.

Based on http://addyosmani.com/writing-modular-js/

### CODE REVIEW

**Comment by davidtheclark** [comment]
I'd rather not expose the global by default, but only if it's _not_ a CommonJS environment. Does that make sense?

**Comment by esseb** [comment]
Yeah, that would probably work.

**Comment by davidtheclark** [comment]
@esseb : Could you pull master (after 60e346fff16799eb5c22124be334e7b96b05fe5e) and see if it works for you?

**Comment by esseb** [comment]
@davidtheclark master works great for my purpose.

**Comment by davidtheclark** [comment]
Published in 1.1.0.

**Pull request closed without merging**
